from settings import SKSP, SEPARATOR


skills = [
    "ancestral call",
    "ancestral leap",
    "ancestral rite",
    "body_slam",
    "brutal swiftness",
    "crimson charge",
    "danger sense",
    "defiant roar",
    "frenzy",
    "intimidating presence",
    "last stand",
    "overpower",
    "primal roar",
    "reckless strike",
    "relentless",
    "relentless advance",
    "rending strike",
    "savage charge",
    "spirit guidance",
    "war paint",
    "war shout",
]

spells = [
    "absent mind",
    "acid blast",
    "acid fangs",
    "acid rain",
    "acid vulnerability",
    "agility boost",
    "all pain",
    "amorphic armour",
    "angels hymn",
    "animate dead",
    "asphyxiation vulnerability",
    "billow of miasma",
    "bitter apathy",
    "black death",
    "blizzard",
    "blizzard storm",
    "bonded spirits",
    "bone shatter",
    "brilliance",
    "call demonic armour",
    "call grimoire",
    "call lightning",
    "call mind control device",
    "cancellation",
    "cat eyes",
    "cause despair",
    "celestial disposition",
    "cellular asphyxia",
    "chain lightning",
    "chant of death",
    "chaos bane",
    "chaos bolt",
    "chaos cube",
    "chaos immolation",
    "chaos lance",
    "chaos wall",
    "charm undead",
    "chill touch",
    "circle of darkness",
    "circle of protection",
    "cold vulnerability",
    "colored lights",
    "colourful berry",
    "confusion",
    "conjure earth elemental",
    "conjure fire elemental",
    "corrosive wind",
    "crash all",
    "crash all in mud",
    "create clone",
    "crumbling feet",
    "cure demon",
    "daggers of ice",
    "dark absolution",
    "dark embryo",
    "dark force",
    "dark teach",
    "darkfire",
    "death armour",
    "death defying feat",
    "death fog",
    "death sanctification",
    "deathslash",
    "demonic blood",
    "demonic rage",
    "demonic shield",
    "demonic test",
    "detect magical potential",
    "devastating hate",
    "dispel good",
    "dissolve",
    "divine aura",
    "divorce",
    "dragon breath",
    "drain power",
    "draining mine",
    "earthslide",
    "electric vulnerability",
    "electro-crush",
    "elemental disarray",
    "empyreal bastion",
    "enchant item",
    "enchanted blast",
    "energy consumption",
    "enslavement",
    "epilepsy",
    "eye for an eye",
    "eye of otus",
    "feminist chant",
    "fire vulnerability",
    "fireclaws",
    "flaming pestilence",
    "flash of power",
    "flesh rot",
    "flesh to stone",
    "fool's gold",
    "force of nature",
    "freezing wind",
    "frost arrow",
    "frost globe",
    "frozen breath",
    "gaseous form",
    "ghost story",
    "giant strength",
    "globes of death",
    "glue",
    "golden dawn",
    "golden mantle",
    "golden meteor",
    "good berry",
    "grave stench",
    "greater acid invulnerability",
    "greater asphyxiation invulnerability",
    "greater fire invulnerability",
    "greater phantom summoning",
    "greater physical invulnerability",
    "haste",
    "hinge door",
    "hole",
    "hour of mercy",
    "howl from beyond",
    "hurricane",
    "hypnotic gaze",
    "ice storm",
    "immunal disorder",
    "indomitable spirit",
    "infinity reincarnation",
    "insect plague",
    "insect plaque",
    "jigoku blade",
    "jolts",
    "lava storm",
    "lesser acid invulnerability",
    "lesser asphyxiation invulnerability",
    "lesser physical invulnerability",
    "levitate object",
    "life leech",
    "lightbringer",
    "lullaby",
    "mabanon's whip",
    "macho mosh",
    "mages bane",
    "magical storm",
    "magical transfixion",
    "magical vestment",
    "magical vulnerability",
    "magical wave",
    "major energy drain",
    "major life leech",
    "major magical resistance",
    "mana short",
    "mark of cain",
    "mental vision",
    "mental watch",
    "metamorphosis",
    "mind control",
    "mind tempest",
    "missile storm",
    "mist haze",
    "moaning laughter",
    "money is power",
    "mystic vision",
    "neural internecion",
    "pain",
    "paranoia",
    "phantom armour",
    "phantom sickle",
    "phantom steed",
    "pigeon melody",
    "planar rescue",
    "poison cloud",
    "poison vulnerability",
    "power transfer",
    "power word",
    "prismatic spray",
    "protection from evil",
    "protection from good",
    "psionic vulnerability",
    "radiance",
    "rain dance",
    "rain of stars",
    "random reincarnation",
    "recall hunter",
    "recognize pattern",
    "reflector shield",
    "restore",
    "riddle",
    "rock to mud",
    "score of the steadfast",
    "screaming mind",
    "seedling",
    "sensory overload",
    "shadow shield",
    "sharp nails",
    "shatter limb",
    "shriek",
    "silence",
    "sleight of hand",
    "slow person",
    "snail shell",
    "snowstorm",
    "solar flare",
    "song of david",
    "song of glory",
    "song of samson",
    "song of satan",
    "song of woe",
    "soulsuck",
    "spiritual hammer",
    "staff light",
    "starburst",
    "starcore",
    "starlight crescent",
    "starshards",
    "stone to flesh",
    "stonefist",
    "stoneshoes",
    "suffocation",
    "summon demonic guardian",
    "summon greater hunter",
    "summon greater spores",
    "summon icicles",
    "summon lesser hunter",
    "summon lesser spores",
    "summon minions",
    "summon orb of reflection",
    "summon phantom sickle",
    "summon shadow",
    "summon swarm",
    "sunlight arc",
    "swords to plowshares",
    "symmetry in body",
    "tale of the owl",
    "tale of the thief",
    "tenrai blade",
    "thermal drain",
    "thorn spray",
    "tortoise nervosa",
    "touch of darkness",
    "touch of death",
    "touch of judas",
    "true distant blizzard storm",
    "unholy absolution",
    "unholy gift",
    "viscous flesh",
    "voids of life",
    "vortex magica",
    "war song",
    "warriors bane",
    "watery breath",
    "weary arms",
    "wildfire",
    "wither",
]


if __name__ == "__main__":
    for skill in skills:
        print(f"help {SKSP} {skill};echo {SEPARATOR};")
