SEPARATOR = "-" * 51
SKSP = "skill"
BASE_PATH = "../../../zCreator_data/data/"
TMP_PATH = "../../zCreator_data/tmp/"


costs_file = f"{SKSP}s.chr"
helps_file = f"help_{SKSP}.chr"


UNKNOWN = {
    "skills": [
        "alternate magics",
        "ambush",
        "amras' touch",
        "apply makeup",
        "art of bushido",
        "assassins dream poison",
        "augment darkness",
        "avoid fate",
        "backstab",
        "blinding dust",
        "cabinetry",
        "control summoning",
        "creative accounting",
        "crowd thievery",
        "damage awareness",
        "dark ritual",
        "demon and devil lore",
        "demon control",
        "disarm traps",
        "disc trick",
        "disguise",
        "distract",
        "double thrust",
        "drow poison",
        "dweomercraft",
        "dweomersight",
        "enhanced evasion",
        "evil omens",
        "evocation",
        "facilitating payments",
        "farsight",
        "find herbs",
        "find traps",
        "focus dark energies",
        "forgery",
        "glance",
        "grapple",
        "hand of evil poison",
        "herbal eyedrops",
        "herbal floating disc",
        "herbal invisibility",
        "herbal see invisible",
        "herbal smoke resistance",
        "hoodwink",
        "imitation",
        "immortality",
        "impale",
        "invocation",
        "killer instinct",
        "magical engineering",
        "magical lore",
        "magical transformation",
        "make disguise wax",
        "mastery of stealing",
        "mathematics",
        "memorize features",
        "metachrosis",
        "nectar of numbling",
        "nightsight",
        "oil of desecration",
        "order from chaos",
        "ordered mind",
        "particle collision",
        "particle manipulation",
        "peer",
        "pick locks",
        "pick pockets",
        "possessions",
        "power manipulation",
        "purse evaluation",
        "purse-cutting",
        "quantum sleight",
        "ritual of black eternity",
        "running red",
        "senseliving",
        "sleight",
        "slip",
        "smoke bomb",
        "sneak",
        "soul manipulation",
        "spellcraft",
        "steal",
        "strangle",
        "suicide",
        "summon mastery",
        "thieves kiss poison",
        "thrust",
        "transmutation",
        "transposition",
        "trapping",
        "triple thrust",
        "tumbling",
        "warcry",
    ],
    "spells": [
        "acid fangs",
        "angels hymn",
        "billow of miasma",
        "bitter apathy",
        "black death",
        "call demonic armour",
        "call grimoire",
        "call mind control device",
        "cancellation",
        "cat eyes",
        "cellular asphyxia",
        "chain lightning",
        "chaos bane",
        "chaos bolt",
        "chaos lance",
        "crash all",
        "crumbling feet",
        "cure demon",
        "daggers of ice",
        "dark absolution",
        "dark force",
        "darkfire",
        "death defying feat",
        "demonic blood",
        "demonic rage",
        "demonic shield",
        "demonic test",
        "detect magical potential",
        "dispel good",
        "divine aura",
        "earthslide",
        "energy consumption",
        "epilepsy",
        "feminist chant",
        "fireclaws",
        "fool's gold",
        "force of nature",
        "frost globe",
        "frozen breath",
        "ghost story",
        "hinge door",
        "hole",
        "hour of mercy",
        "immunal disorder",
        "infinity reincarnation",
        "levitate object",
        "lullaby",
        "macho mosh",
        "mages bane",
        "magical storm",
        "magical transfixion",
        "missile storm",
        "moaning laughter",
        "neural internecion",
        "phantom sickle",
        "phantom steed",
        "pigeon melody",
        "planar rescue",
        "protection from good",
        "rain dance",
        "recall hunter",
        "recognize pattern",
        "riddle",
        "screaming mind",
        "sharp nails",
        "shatter limb",
        "silence",
        "sleight of hand",
        "snail shell",
        "song of david",
        "song of glory",
        "song of samson",
        "song of satan",
        "song of woe",
        "spiritual hammer",
        "summon demonic guardian",
        "summon greater hunter",
        "summon lesser hunter",
        "symmetry in body",
        "tale of the owl",
        "tale of the thief",
        "thermal drain",
        "viscous flesh",
        "voids of life",
        "vortex magica",
        "war song",
        "warriors bane",
        "watery breath",
        "weary arms",
        "wildfire",
    ],
}
